version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build  # Builds the project

artifacts:
  files:
    - '**/*'
  base-directory: build     # Focus on files in 'build/'
  discard-paths: no         # Keep paths during artifact packaging
